scylladb:
  host: "scylla-db.aman-dw.in:9042"
  username: scylladb
  password: password
  keyspace: employee_db

redis:
  enabled: false
  host: redis.aman-dw.in:6379
  password: password
  database: 0
